{% set name = "cosmosis-standard-library" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/joezuntz/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fc815e5068a1e212c1af8af2106c42e14881f466b462c0a6c918a144e5fbb30c

build:
  number: 0
  skip: True  # [win or (py < 36)]
  detect_binary_files_with_prefix: True
  missing_dso_whitelist:
    - "*/liblimber.so"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - cosmosis
    - cython
    - mpich          # [mpi == "mpich"]
    - openmpi        # [mpi == "openmpi"]
    - libblas
    - libcblas
    - liblapack
    - cfitsio
    - gsl
    - fftw
    - scipy
    - astropy
    - numpy
    - matplotlib
    - fitsio
    - pyyaml
    - scikit-learn
    - fast-pt
  run:
    - python
    - {{ pin_compatible('cosmosis', max_pin='x.x') }}

test:
  commands:    
    - test -f $PREFIX/lib/cosmosis-standard-library/likelihood/planck2018/planck_interface.so

about:
  home: https://github.com/joezuntz/cosmosis-standard-library
  summary: 'CosmoSIS is a cosmological parameter estimation code.'
  description: |
    It is a framework for structuring cosmological parameter estimation with a
    focus on flexibility, re-usability, debugging, verifiability, and code 
    sharing in the form of calculation modules. It consolidates and connects 
    together existing code for predicting cosmic observables, and makes mapping
    out experimental likelihoods with a range of different techniques much more
    accessible.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://cosmosis.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - vitenti
    - marcpaterno
