{% set name = "cobaya" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CobayaSampler/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e6dfa754673a8471532690bb2ea03424142812933287d9e298a690581dd70620

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - camb
    - numpy >=1.17.0
    - scipy >=1.5
    - pandas >=1.0.1
    - PyYAML >=5.1
    - requests >=2.18
    - fuzzywuzzy >=0.17
    - packaging
    - tqdm
    - portalocker >=2.3.0
    - dill >=0.3.3

about:
  home: https://github.com/CobayaSampler/cobaya
  summary: 'Cobaya, a code for Bayesian analysis in Cosmology'
  description: |
    Cobaya (code for bayesian analysis, and Spanish for Guinea Pig) is a 
    framework for sampling and statistical modelling: it allows you to explore 
    an arbitrary prior or posterior using a range of Monte Carlo samplers 
    (including the advanced MCMC sampler from CosmoMC, and the advanced nested 
    sampler PolyChord). The results of the sampling can be analysed with 
    GetDist. It supports MPI parallelization (and very soon HPC 
    containerization with Docker/Shifter and Singularity).
  license: LGPL-3.0
  license_file: LICENSE.txt
  doc_url: https://cobaya.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - vitenti
    - marcpaterno
